// Code generated by mockery v1.0.0. DO NOT EDIT.

package vulndb

import mock "github.com/stretchr/testify/mock"

// MockVulnDB is an autogenerated mock type for the VulnDB type
type MockVulnDB struct {
	mock.Mock
}

type VulnDBBuildArgs struct {
	Targets         []string
	TargetsAnything bool
}

type VulnDBBuildReturns struct {
	_a0 error
}

type VulnDBBuildExpectation struct {
	Args    VulnDBBuildArgs
	Returns VulnDBBuildReturns
}

func (_m *MockVulnDB) ApplyBuildExpectation(e VulnDBBuildExpectation) {
	var args []interface{}
	if e.Args.TargetsAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.Targets)
	}
	_m.On("Build", args...).Return(e.Returns._a0)
}

func (_m *MockVulnDB) ApplyBuildExpectations(expectations []VulnDBBuildExpectation) {
	for _, e := range expectations {
		_m.ApplyBuildExpectation(e)
	}
}

// Build provides a mock function with given fields: targets
func (_m *MockVulnDB) Build(targets []string) error {
	ret := _m.Called(targets)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(targets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
